title: Portfolio
description: Personal portfolio
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"  # or "default", "air", "contrast", etc.

baseurl: "/portfolio"

# Author profile (sidebar / footer)
author:
  name   : "Thanh Dat Hoang"
  avatar : "/assets/images/Dat_photo.jpg"       # optional but recommended
  bio    : "Astrophysics PhD transitioning to data science & engineering."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/tdhoang0412"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/tdhoang0412" 
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:tdhoang412@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/tdhoang0412"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/tdhoang0412"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:tdhoang412@gmail.com"
copyright: "Thanh Dat Hoang"

