title: Thanh Dat Hoang
description: Personal portfolio
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"  # or "default", "air", "contrast", etc.
